export const defaultSiteCopy = {
  siteName: "浮光笔记",
  siteCode: "FUGUANG NOTES",
  authorName: "周川",
  navNotes: "笔记",
  navTopics: "专题",
  navAdmin: "写作后台",
  navCompareA: "A 版",
  navCompareB: "B 版",
  navCompareC: "C 版",
  aEyebrow: "思考 · 技术 · 生活",
  aTitleLine1: "在喧嚣里，",
  aTitleLine2: "打捞思想的微光。",
  aIntro: "你好，我是周川。这里收录我关于技术、阅读与生活的长期笔记。愿这些尚未完成的思考，也能为你照亮一小段路。",
  aCta: "开始阅读",
  aTodayLabel: "今日札记",
  aTodayQuote: "不要急着成为答案，先成为一个好问题。",
  aTodaySignature: "— 写在盛夏",
  aFeaturedTitle: "精选文章",
  aRecentTitle: "最近笔记",
  aTopicsTitle: "按主题浏览",
  aAboutTitle: "关于这里",
  aAboutText: "笔记并非结论，而是思考留下的脚印。保持好奇，持续记录。",
  footerMotto: "写作是与时间相处的一种方式。",
  footerLegal: "© 2026 周川 · Built with curiosity.",
  bStatus: "ONLINE",
  bPath: "~/fuguang/notes main*",
  bTitleLine1: "思考的轨迹，",
  bTitleLine2: "在深夜持续发光",
  bIntro: "关于技术、创造与日常观察的长期记录。这里没有最终答案，只有持续更新的思考版本。",
  bCommand: "cd ./latest-notes",
  bFeaturedTitle: "精选记录",
  bRecentTitle: "最近更新",
  bFilterTitle: "FILTER_BY_TAG",
  bQuote: "保持开放，保持未完成。",
  cKicker: "A QUIET INDEX OF IDEAS",
  cTitle: "把零散的思考，整理成一座可以漫游的花园。",
  cIntro: "这里收录技术实践、阅读札记与日常观察。每一篇笔记都可以被检索、连接，也可以继续生长。",
  cSearchPlaceholder: "搜索标题、摘要或主题…",
  cFeaturedTitle: "值得从这里开始",
  cRecentTitle: "最近更新",
  cBrowseTitle: "主题索引",
  cAsideTitle: "持续写作",
  cAsideText: "把注意力放在值得长期思考的问题上。",
} as const;

export type SiteCopy = { [K in keyof typeof defaultSiteCopy]: string };

export const siteCopyFields: Array<{ key: keyof SiteCopy; label: string; group: string; multiline?: boolean }> = [
  { key: "siteName", label: "站点名称", group: "全站" }, { key: "siteCode", label: "英文标识", group: "全站" }, { key: "authorName", label: "作者名", group: "全站" },
  { key: "navNotes", label: "导航：笔记", group: "全站" }, { key: "navTopics", label: "导航：专题", group: "全站" }, { key: "navAdmin", label: "导航：后台", group: "全站" },
  { key: "navCompareA", label: "A 版名称", group: "全站" }, { key: "navCompareB", label: "B 版名称", group: "全站" }, { key: "navCompareC", label: "C 版名称", group: "全站" },
  { key: "aEyebrow", label: "顶部小标题", group: "A 版" }, { key: "aTitleLine1", label: "主标题第一行", group: "A 版" }, { key: "aTitleLine2", label: "主标题第二行", group: "A 版" },
  { key: "aIntro", label: "个人介绍", group: "A 版", multiline: true }, { key: "aCta", label: "阅读按钮", group: "A 版" }, { key: "aTodayLabel", label: "札记标签", group: "A 版" },
  { key: "aTodayQuote", label: "札记引用", group: "A 版", multiline: true }, { key: "aTodaySignature", label: "札记落款", group: "A 版" }, { key: "aFeaturedTitle", label: "精选栏目名", group: "A 版" },
  { key: "aRecentTitle", label: "最近栏目名", group: "A 版" }, { key: "aTopicsTitle", label: "主题栏目名", group: "A 版" }, { key: "aAboutTitle", label: "关于标题", group: "A 版" }, { key: "aAboutText", label: "关于正文", group: "A 版", multiline: true },
  { key: "bStatus", label: "在线状态", group: "B 版" }, { key: "bPath", label: "终端路径", group: "B 版" }, { key: "bTitleLine1", label: "主标题第一行", group: "B 版" }, { key: "bTitleLine2", label: "主标题第二行", group: "B 版" },
  { key: "bIntro", label: "介绍文字", group: "B 版", multiline: true }, { key: "bCommand", label: "命令按钮", group: "B 版" }, { key: "bFeaturedTitle", label: "精选栏目名", group: "B 版" }, { key: "bRecentTitle", label: "最近栏目名", group: "B 版" }, { key: "bFilterTitle", label: "筛选标题", group: "B 版" }, { key: "bQuote", label: "侧栏引用", group: "B 版", multiline: true },
  { key: "cKicker", label: "顶部小标题", group: "C 版" }, { key: "cTitle", label: "主标题", group: "C 版", multiline: true }, { key: "cIntro", label: "介绍文字", group: "C 版", multiline: true }, { key: "cSearchPlaceholder", label: "搜索提示", group: "C 版" },
  { key: "cFeaturedTitle", label: "精选栏目名", group: "C 版" }, { key: "cRecentTitle", label: "最近栏目名", group: "C 版" }, { key: "cBrowseTitle", label: "主题栏目名", group: "C 版" }, { key: "cAsideTitle", label: "侧栏标题", group: "C 版" }, { key: "cAsideText", label: "侧栏正文", group: "C 版", multiline: true },
  { key: "footerMotto", label: "页脚短句", group: "全站" }, { key: "footerLegal", label: "页脚版权", group: "全站" },
];
